/贵在坚持/

严重警告：尿毒症

* 还阳卧　
  身体自然平躺，髋关节放松，腿似环，两脚心相对，脚后跟最好直对着会阴（如果能顶着会阴最好）两手心放于大腿根部附近，掌心向着腹部。
  仰卧由于着床面积大，压迫力较小，身体更容易放松，身体的放松加上一定的姿势，可以很快的把阳气和肾气充盈起来。
  肾阳气相当于命门的真火――一个生命力的大小关键就是看命门的阳气是否充足。摆这个姿势，就是为了更有利于肾阳气的充足。此式补肾的作用明显。
* 按摩腹部
* 压脐
* 背部撞墙
* 胡海牙老师的瞬间强肾功
  双手握拳，拳心虚空，贴在肾腧位置，利用膝关节的上下抖动进行反复摩擦，双拳不动，双脚随着身体抖动轻微起踮，感觉到腰部轻微发热为止。
  （肾俞穴的位置 肚脐眼位置的背后命门旁开1.5寸）
* 提肾功

  端坐凳上，双脚踏地，脚宽同肩，双手放大腿上，掌心向上或向下均可。坐时注意不坐满凳，可坐在凳边。练习数日，熟练后，可不拘形式，随时随地可练。 
  集中思想于下部（即会阴部，详见下文）。随着呼吸，下部一提一放，一紧一松，即使暗劲往上往里提缩，如忍小便状。 
  呼吸采取腹式顺呼吸法，即呼气时，腹部凹进，同时略用些力将下部上提，也即一紧；吸气时，即将下部随着呼吸凸出而下放，即一松。
  这样，随着呼吸，一紧一松，反复练习。熟练后，即可不管呼吸，随时可提放，紧松，甚至和别人谈话时也可将下部一提一放，一紧一松，但提放、紧松的次数不能多。 
  所谓下部，男女不同；在男性系指睾丸、精索、阴茎、肛门括约肌等；在女性系指大小阴唇、阴道、阴蒂、肛门括约肌等。 
  采用此法治病，每日几次不限，随时随地可练，但每次只能提缩十几次，最多不能超过二十次。练过一次后，必须再过一段时间再练。 
提肾功 - 注意事项 
　　（一）每次提缩不能超过二十下，否则会引起脑顶紧张不适； 
　　（二）有高血压病史的人每次提缩次数要减少，否则可能引起血压升高，头晕脑胀； 
　　（三）有失眠症者晚上不能练，以免引起失眠。 
提肾功 - 适应症
——膀胱炎、肾结核、血尿、前列腺炎、遗精、肾结石、功能性子宫出血、胃肠炎、腰脊椎肥大性关节炎、再生不良性贫血、神经衰弱等。　　提肾功除对泌尿系统和生殖系统病症能取得一定疗效外，对全身性其它慢性病也有一定的治疗作用。

* 拍手功
* 握固
* 举手功
* 脚棍
  前不过脚趾，后不过脚心，前后滚动
  滚棍时一定要用意不用力
* 转手腕、脚腕
* 踮脚
常踮脚益处多
* 厕所
  小便的时候要精神专注，保护肾气，千万不要说话，因为说话会泻肾气的。同时，小便也不能用力，太用力也容易耗损肾气。
上厕所大小便的时候，一定要咬牙，咬牙能固摄住肾气，尤其是在肾精上损害偏大的男人。这是为什么呢？因为牙为肾之齿，是肾精华的外现。但不能乱咬牙，死咬着不放更耗肾气；而应该是“肾齿两枚如咬”，“如”就是好像的意思，就是好像有两个枣核在两个后槽牙之间，微微地咬着。解手的时候处于一个吸气、气往里收的状态，是不开泄的。咬牙，并且提起脚后跟，就等于补了肾气。

* 叩齿法
齿是骨之余，是骨头的余气，而肾又主骨。当人到了一定岁数，肾气就会逐渐衰弱，牙齿也会松动。对这种情况，我们可以反过来想，如果牙齿很坚固，那么是不是肾气就会很足呢？如果暂时不方便调理肾，那么我们可以先坚固牙齿。牙齿里的经络和肾经是相通的，只要坚固牙齿，它就可以对肾起一个反固的作用，就可以让肾强壮。要知道，人不可能牙齿很强壮而肾很虚弱，这是绝不可能的，因为它们是同步的。所以，如果我们不便直接地去调养肾，那么就健壮牙齿，这是最好的补肾方法。

 健壮牙齿的好方法就是多叩齿，早上300下，用上下两排两个牙齿撞击就行了，就这么简单。
 注意：撞击的地方主要是后面的槽牙，不要让前面的牙先叩。
* 习惯
  1、 每日雷打不动睡满7小时，改善疲惫状态。注意睡眠不要超过8小时，睡多了也会让你疲惫的。
  2、 改掉睡前饮水的习惯，晚上不是补水时间，因为肾虚时水液代谢不畅，容易水肿。
  3   睡前和起床前，按摩腹部,按肚脐
* 人体经络运行时间与生理系统的反应     
  
《黄帝内经》记载，每天十二时辰和人的十二经络的运行是有规律的，掌握这个规律，养成良好的生活习惯，你就会得到健康的身体。简单介绍如下：

十二时辰 	对应 	十二正经 	生理系统
子时 	23:00—1:00 	足少阳胆经 	骨髓造血
丑时 	1:00—3:00 	足厥阴肝经 	肝脏修复
寅时 	3:00—5:00 	手太阴肺经 	呼吸系统
卯时 	5:00—7:00   	手阳明大肠经 	大肠
辰时   	7:00—9:00 	足阳明胃经 	胃
巳时   	9:00—11:00 	足太阴脾经 	脾脏
午时 	11:00—13:00 	手少阴心经 	肝脏造血
未时 	13:00—15:00 	

手太阳小肠经
	小肠
申时 	15:00—17:00 	足太阳膀胱经 	膀胱
酉时 	17:00—19:00 	足少阴肾经 	肾脏
戌时 	19:00—21:00 	手厥阴心包经 	心脏、大脑
亥时 	21:00—23:00 	手少阳三焦经 	免疫系统修复

       首先，整个身体的自然修补时间，是在21点到凌晨3点。这段时间一定要休息，如不能休息，也一定要停止一切活动。
       21点到23点的时间，是免疫系统运作的时间，特别是小朋友的免疫系统还不健全，因此小学 6 年级以前的小朋友最好在21点左右就寝。这个时候不要做大伤元气的事,以免中风或面瘫痪.
       而23点到凌晨1点是骨随造血时间、正是补血的时候
       凌晨1点到3点是肝脏修复的时间,   
        凌晨3 点到5点是呼吸系统运作的时间。
       其中凌晨4点是我们脉搏最弱，心跳最慢的时候，所以，我们在医学上有所谓的〈危险4点钟〉所以家里如有老年人，这个时间就要特别注意。早晨的运动最好是在 5 点以后再出门，接下来
       5 点到7 点是大肠蠕动最旺盛的时间是吃早餐时间，7点到9点则是最活跃的时间，
       9点到11点是脾脏活动时间。
       到了午时〈上午的11点到下午1点〉与子时〈晚上23点到凌晨1点〉由于身体在造血因此我们需要较好的休息，所以在这段时间好好的休息，就不容易贫血。因此，我们知道只要遵循自然法则，那么我们的身体就可以得到很好的复原，如此这般，我们在工作会十分有精神在休息得到全然的放松。
       下午13点到15点是小肠运作的时间，所以午餐最好在下午13点吃，
       13点到15点膀胱运作时间，这段时间要多喝水是重要喝水时间。效果也最显著，如果肾脏与膀胱不好的人，最好在这段时间喝下500 的水。
       下午17 点到19 点是肾脏活动的时。
       19点到21点为心脏与脑神经系统活跃的时间。
